// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsaNdSU0xedWrvmSPu45uDIAOqDhUqDE',
    appId: '1:77981689708:web:6263bd28e0e8ceb614f549',
    messagingSenderId: '77981689708',
    projectId: 'wechat-4e23c',
    authDomain: 'wechat-4e23c.firebaseapp.com',
    databaseURL: 'https://wechat-4e23c-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-4e23c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7fmb-sCFDOFV5tzqI4pxvr4YJY4aXr48',
    appId: '1:77981689708:android:f2f81e4f7bc1321814f549',
    messagingSenderId: '77981689708',
    projectId: 'wechat-4e23c',
    databaseURL: 'https://wechat-4e23c-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-4e23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmD8iipoa7Ls_FyuHphML0X855UD31b8',
    appId: '1:77981689708:ios:aa7125207836e4ae14f549',
    messagingSenderId: '77981689708',
    projectId: 'wechat-4e23c',
    databaseURL: 'https://wechat-4e23c-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-4e23c.appspot.com',
    androidClientId: '77981689708-d525h221cp1u232ckt1qehlqtrgni063.apps.googleusercontent.com',
    iosClientId: '77981689708-gu4sq19ba1sd5qies9b3t149l9cb4806.apps.googleusercontent.com',
    iosBundleId: 'com.example.cow1',
  );
}
